### PR TITLE
Add `Generic` support for empty constructors

### PR DESCRIPTION
**Pull request by bitonic**
This change is [Reviewable](https://reviewable.io/reviews/galoisinc/cereal/49)

### CODE REVIEW

**Comment by elliottt** [comment]
I'm a little conflicted on this because of the implementation of `get`. At the very least, could you change it to `fail` instead, so that it's a recoverable error instead?

**Comment by bitonic** [comment]
Well... I don't think it's a "parsing" failure: it's more that no such value can exist, and so you return bottom.

For example, consider

```
data Foo = Foo {fooBottom :: Void}
```

With my implementation, serialization and deserialization roundtrips (denotationally, at least).

If we want to make parsing fail, then we should have encoding to fail too somehow.

**Comment by glguy** [comment]
The implementation of gPut for V1 should be something like

    gPut v = v `seq` return ()

You'll never have a non-bottom value to pass to this function and seq'ing that ensures that the correct error is raised were someone to pass such a bottom in.

The implementation for gGet for V1 would then rightly be

    gGet = fail "V1.gGet"

While it makes sense for this instance to exist so that we can derive instances for empty types making them suitable for using in cases like serializing Either EmptyType NonEmptyType where Either requires an instance for both of its instances, these instances should not be introducing new bottoms or ignoring the ones passed in.

**Comment by bitonic** [comment]
I think the decision is: do we want to serialize empty types?

My PR answers "yes". The only value that you can have in an empty type is bottom, so you don't write anything. When you deserialize, you get that same bottom.

If we answer "no", then we can do what @glguy suggests.

Note that `binary` answers "yes", which is where I got that code from (with a slightly better error message). I don't have a particularly strong opinion, although it's hard to predict the ramifications of this decisions.

**Comment by bitonic** [comment]
Although, I did add this because I needed it in a fairly large codebase. Which makes me wonder why we needed it. I'll get back to you ;)

**Comment by glguy** [comment]
Binary answers "no" to this question in general. Note that it does not preserve bottoms when serializing an Int

**Comment by bitonic** [comment]
`Int`s are different: they contain other data apart from bottom.

For what concerns `binary`, this is what I'm referring to: https://github.com/kolmodin/binary/blob/master/src/Data/Binary/Generic.hs#L35 .

I don't have a strong opinion regarding this.

**Comment by elliottt** [comment]
I agree with @glguy's analysis, and would prefer that we don't serialize empty types. Does that behavior still support your use case?

**Comment by bitonic** [comment]
Sorry about the delay, I didn't have time to check. I'll try to check tomorrow.

**Comment by glguy** [comment]
Fixed in 204894ae2362accb5ea2e5554e1928cb739d4845

**Pull request closed without merging**
