### PR TITLE
Support GHC 9.4

### PR DESCRIPTION
**Pull request by parsonsmatt**
This PR supports GHC 9.4

### CODE REVIEW

**Comment by amigalemming** [comment]
Conversion to Word will fail on a 32-bit machine.

**Comment by elliottt** [comment]
> Conversion to Word will fail on a 32-bit machine.

It looks like this` definition is only present if the word size is >= 64.

**Comment by parsonsmatt** [comment]
Relevant notes in migration guide: https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.4#word64int64-use-word64int64

> Before 9.4, Int64/Word64 were wrappers for Int#/Word# on 64-bit architectures and for Int64#/Word64# on 32-bit architectures. Now the latter are always used (Int64#/Word64#). Users of the unboxed values must use Int64#/Word64# primops on every architecture.

So, I think the point of this change is that 64-bit and 32-bit architecture have the same constructors/types, and stuff like using CPP to check the bit count is no longer necessary.

This suggests to me that the correct logic is probably more like:

```haskell
#if MIN_VERSION_base(4,17,0)
    -- data Word64 = W64# Word64#
#else
#    if WORD_SIZE_IN_BITS < 64
    -- data Word64 = W64# Word64#
#    else
    -- data Word64 = W64# Word#
#    endif
#endif
```

Or, collapsing cases,

```haskell
#if MIN_VERSION_base(4,17,0) || WORD_SIZE_IN_BITS < 64
    -- data Word64 = W64# Word64#
#else
    -- data Word64 = W64# Word#
#endif
```

I haven't read more deeply than the release notes and migration guide, though, and it's a prelease, so it may yet change.

**Comment by mpilgrem** [comment]
I have sorted of tested this pull request by using the fork to build Stack (which depends on `cereal`) with GHC 9.4.1.

**Comment by glguy** [comment]
should be fixed in 0.5.8.3

**Pull request closed without merging**
