### PR TITLE
Add bytesRead to Data.Serialize.Get

### PR DESCRIPTION
**Pull request by Ongy**
After another 2 years https://github.com/GaloisInc/cereal/issues/8 gets a PR.

I added the current byte count to the state of Get.
Running the benchmark locally, I can't see a major performance hit (only ran each version once though).

I'm a bit unsure about the `MonadPlus` instance and how to add tests. Can you please have a look at those?

Also https://github.com/GaloisInc/cereal/issues/8 also mentions the idea of a bytesWritten. Looking at the current `Data.Serialize.Put` I don't think it is possible. Was the rewrite already done? Are there plans to go to something similar to `Data.Serialize.Get`?

### CODE REVIEW

**Comment by Ongy** [comment]
So I played around with bytesWritten for `Data.Serialize.Put` and I don't think it's feasable without a noticable performance loss.

Even putting in `seq` to force order got me 10% longer times in the benchmarks.

**Comment by elliottt** [comment]
I think that the `mplus` implementation makes sense -- you don't need a `w` parameter in the `try` function, as you want to reuse the original `w0` value passed in.

Have you been able to benchmark this to see if it causes much performance loss in `Get`?

**Comment by Ongy** [comment]
I have tested this on 2 machines. My laptop (i3-2350M) and my pc (i7-2700k) with the benchmark in the repo:
[Laptop-head](http://lpaste.net/3467243715565715456) [Laptop-PR](http://lpaste.net/5181104102402162688)
[PC-head](http://lpaste.net/6991668851888881664) [PC-PR](http://lpaste.net/8280094783683166208)

I don't have any other code I can use to do any serious testing.

**Comment by elliottt** [comment]
It looks like `put` is going to build a big thunk, could you make the length parameter to it strict?

**Comment by elliottt** [comment]
Looks like I dropped the ball a little bit on this, thanks for the contribution!

**Pull request merged**
